### ISSUE TITLE
kcli list vm doesn't show IP when on a bridged network

### ISSUE THREAD

**Issue by ferni7** [karmab/kcli#488]
Hi Team,

New to kcli, playing around with it. I setup my ubuntu host to have a bridged network and created a VM attached to that network. It gets an IP from my dhcp server, accessible on the network as expected but for some reason the kcli list vm doesn't show an IP against it, any ideas?

```
kcli list network
Listing Networks...
+---------+--------+------------------+-------+---------+--------+
| Network |  Type  |       Cidr       |  Dhcp |  Domain |  Mode  |
+---------+--------+------------------+-------+---------+--------+
| br0     | routed |       N/A        | False |   br0   | bridge |
| default | routed | 192.168.122.0/24 |  True | default |  nat   |
+---------+--------+------------------+-------+---------+--------+


kcli list vm
+------+--------+----+----------------------------------------+-------+------------+
| Name | Status | Ip |                 Source                 |  Plan |  Profile   |
+------+--------+----+----------------------------------------+-------+------------+
| vm1  |   up   |    | ubuntu-20.04-server-cloudimg-amd64.img | kvirt | ubuntu2004 |
| vm2  |   up   |    | ubuntu-20.04-server-cloudimg-amd64.img | kvirt | ubuntu2004 |
+------+--------+----+----------------------------------------+-------+------------+

```

**Comment by karmab** [comment]
make sure you re using a recent enough version of kcli, at some point, the code that installs qemu-guest-agent had a typo, which would only affect ubuntu2004 and later images since they dropped this binary from the images.

Cloudinit in the vm should install qemu-guest-agent if using latest version, you can check it by sshing the vm or by mounting the corresponding vm1.iso (either on the hypervisor or within the vm) and having a look at the generated user-data

**Comment by Ferni7** [comment]
You're right, the qemu-guest-agent wasn't installed. I ssh'ed in and installed it and now I get my vm IP with `kcli list vm`

If i create a VM with default network(NAT) then i get the ip with `kcli list vm` even though that vm doesn't have qemu-guest-agent installed

What should be installing the guest agent?

```
kcli version
version: 99.0 commit: 2a0861f 2022/12/21 Available Updates: False
```

**Comment by Ferni7** [comment]
Ok mounted the vm2.iso file, nothing about installing quemu-guest-agent in here...

```
cat user-data 
#cloud-config
final_message: kcli boot finished, up $UPTIME seconds
hostname: vm2
ssh_pwauth: True
disable_root: false
ssh_authorized_keys:
- ssh-rsa xxxx
```

**Comment by karmab** [comment]
ah, I misread your initial description.
qemu-guest-agent gets installed when the network is marked as a bridged, which you can see in the type column of your list network command.
In the case of your br0 network, its type isnt marked as bridge but its Mode says so, so it s misleading.
The typical way to create a bridge is to use standard tools like nmcli and then they get automatically visible in the list networks output, but my understanding is that you created manually the corresponding network xml to your bridge.

Anyway, I should also install the guest agent in your case, so let me fix that


Regards,

**Comment by Ferni7** [comment]
I just used the ip link command to create the bridged interface.

Out of interest, Why wouldn’t we want the qemu-guest-agent installed on all
machines regardless of network type?

**Comment by karmab** [comment]
we dont want to always install qemu-guest-agent because it's not needed for retrieving vm ips when the vm only belongs to libvirt based networks.
Anyway, I fixed here https://github.com/karmab/kcli/commit/aff1f64035f9bf967f11320c13410e6e62c8e47d !

**Comment by ferni7** [comment]
Ahh ok, I thought that qemu-guest-agent was also so the hypervisor could query/control (ie graceful shutdown) of the VM's as well?

I'm struggling to create a clean bridge network with kcli, Any advice/help appreciated :)
Here is my workflow

1. Create a bridge network using netplan on ubuntu 22.04
```
$ cat /etc/netplan/01-bridge-network.yaml
network:
  version: 2
  ethernets:
    enp0s31f6:
      dhcp4: false
      dhcp6: false
  bridges:
    br0:
      dhcp4: false
      dhcp6: false
      addresses: 
      - 192.168.0.4/23
      routes:
      - to: default
        via: 192.168.0.1
      nameservers:
        addresses:
        - 192.168.0.1
      interfaces:
        - enp0s31f6

$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s31f6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br0 state UP group default qlen 1000
    link/ether b0:7b:25:19:bd:74 brd ff:ff:ff:ff:ff:ff
3: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 06:f7:9a:32:0d:41 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.4/23 brd 192.168.1.255 scope global br0
       valid_lft forever preferred_lft forever
    inet6 fdad:d315:92cb:4e9c:4f7:9aff:fe32:d41/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 1761sec preferred_lft 1761sec
    inet6 fe80::4f7:9aff:fe32:d41/64 scope link 
       valid_lft forever preferred_lft forever
```
2. KCLI see's this new br0 network, see's it's type is bridged, but doesn't have a Domain or Mode (I think I need bridged mode here right?)
```
$ kcli list network
Listing Networks...
+---------+---------+------------------+------+---------+------+
| Network |   Type  |       Cidr       | Dhcp |  Domain | Mode |
+---------+---------+------------------+------+---------+------+
| br0     | bridged |       N/A        | N/A  |   N/A   | N/A  |
| default |  routed | 192.168.122.0/24 | True | default | nat  |
+---------+---------+------------------+------+---------+------+
```
3. virsh doesn't see the bridge network at all
```
virsh net-list --all
 Name      State      Autostart   Persistent
----------------------------------------------
 default   inactive   no          yes
```
4. Create a bridge network with virsh
```
cat bridge-network.yaml
<network>
  <name>host-bridge</name>
  <forward mode="bridge"/>
  <bridge name="br0"/>
</network>

virsh net-define host-bridge.xml
virsh net-start host-bridge
virsh net-autostart host-bridge
```
5. Now virsh shows the host-bridge network
```
$ sudo virsh net-list --all
 Name          State      Autostart   Persistent
--------------------------------------------------
 default       inactive   no          yes
 host-bridge   active     yes         yes
```
6. kcli sees it but it lists the type as routed?
kcli list network
Listing Networks...
+-------------+---------+------------------+-------+-------------+--------+
| Network     |   Type  |       Cidr       |  Dhcp |    Domain   |  Mode  |
+-------------+---------+------------------+-------+-------------+--------+
| br0         | bridged |       N/A        |  N/A  |     N/A     |  N/A   |
| default     |  routed | 192.168.122.0/24 |  True |   default   |  nat   |
| host-bridge |  routed |       N/A        | False | host-bridge | bridge |
+-------------+---------+------------------+-------+-------------+--------+
```

Any help on the cleanest/simplest way to create this bridged network the right way with/for kcli?

**Comment by karmab** [comment]
while it looks confusing, mainly because there are two ways to create such a bridge, I think your commands are actually fine

**Comment by ferni7** [comment]
Sorry - I'm still missing something.

I destroyed and undefined my br0 bridge (it still exists at OS level/netplan).

I tried to run `kcli create network -P bridge=true br0` but it complains this already exists

So instead i created a new br1 network (which has no matching underlying NIC), but if I try to create a VM using it, it rightly complains

```
ferni7@fserver:~$ virsh net-list
 Name   State   Autostart   Persistent
----------------------------------------

ferni7@fserver:~$ kcli create network -P bridge=true br0
Network br0 already exists
ferni7@fserver:~$ kcli create network -P bridge=true br1
Network br1 deployed
ferni7@fserver:~$ kcli list network
Listing Networks...
+---------+---------+------------------+-------+---------+--------+
| Network |   Type  |       Cidr       |  Dhcp |  Domain |  Mode  |
+---------+---------+------------------+-------+---------+--------+
| br0     | bridged |       N/A        |  N/A  |   N/A   |  N/A   |
| br1     |  routed |       N/A        | False |   br1   | bridge |
| default |  routed | 192.168.122.0/24 |  True | default |  nat   |
+---------+---------+------------------+-------+---------+--------+
ferni7@fserver:~$ kcli create vm -i ubuntu2004 vm3 -P nets=[br1] -P memory=8096 -P numcpus=4 
Deploying vm vm3 from profile ubuntu2004...
vm3 not created because Cannot get interface MTU on 'br1': No such device
```
